import { Injectable } from "@nestjs/common";
import { ISeatRepository, IRoomRepository } from "../../../domain/repositories";
import { Seat } from "../../../domain/entities/Seat";
import { GenerateSeatsForRoomInput, GenerateSeatsForRoomOutput } from "./GenerateSeatsForRoomDTO";
import { GenerateSeatsForRoomValidator } from "./GenerateSeatsForRoomValidator";

@Injectable()
export class GenerateSeatsForRoomUseCase {
  constructor(
    private seatRepository: ISeatRepository,
    private roomRepository: IRoomRepository
  ) {}

  async execute(input: GenerateSeatsForRoomInput): Promise<GenerateSeatsForRoomOutput> {
    const errors = GenerateSeatsForRoomValidator.validate(input);
    if (errors.length > 0) {
      throw new Error(`Validation failed: ${errors.join(", ")}`);
    }

    // Verify room exists
    const room = await this.roomRepository.findById(input.roomId);
    if (!room) {
      throw new Error(`Room with ID ${input.roomId} not found`);
    }

    // Generate seats
    const seats: Seat[] = [];
    for (const row of input.rows) {
      for (let seatNumber = 1; seatNumber <= input.seatsPerRow; seatNumber++) {
        const seat = new Seat(
          undefined, // id will be generated by repository/db
          input.roomId,
          row,
          seatNumber,
          true // available by default
        );
        seats.push(seat);
      }
    }

    // Bulk create seats
    const countCreated = await this.seatRepository.createMany(seats);

    return {
      countCreated,
    };
  }
}
