import { Injectable } from "@nestjs/common";
import { IMovieRepository } from "../../../domain/repositories";
import { Movie } from "../../../domain/entities/Movie";
import { CreateMovieInput, CreateMovieOutput } from "./CreateMovieDTO";
import { CreateMovieValidator } from "./CreateMovieValidator";

@Injectable()
export class CreateMovieUseCase {
  constructor(private movieRepository: IMovieRepository) {}

  async execute(input: CreateMovieInput): Promise<CreateMovieOutput> {
    const errors = CreateMovieValidator.validate(input);
    if (errors.length > 0) {
      throw new Error(`Validation failed: ${errors.join(", ")}`);
    }

    const movie = new Movie(
      undefined, // id will be generated by repository/db
      input.title,
      input.description,
      input.duration,
      input.coverImage,
      input.category,
      input.releaseDate,
      input.rating
    );

    await this.movieRepository.create(movie);

    return {
      movieId: movie.id as string,
    };
  }
}
