import { Injectable } from "@nestjs/common";
import { ICinemaRepository, IRoomRepository } from "../../../domain/repositories";
import { Room } from "../../../domain/entities/Room";
import { AddRoomToCinemaInput, AddRoomToCinemaOutput } from "./AddRoomToCinemaDTO";
import { AddRoomToCinemaValidator } from "./AddRoomToCinemaValidator";

@Injectable()
export class AddRoomToCinemaUseCase {
  constructor(
    private cinemaRepository: ICinemaRepository,
    private roomRepository: IRoomRepository
  ) {}

  async execute(input: AddRoomToCinemaInput): Promise<AddRoomToCinemaOutput> {
    const errors = AddRoomToCinemaValidator.validate(input);
    if (errors.length > 0) {
      throw new Error(`Validation failed: ${errors.join(", ")}`);
    }

    // Verify cinema exists
    const cinema = await this.cinemaRepository.findById(input.cinemaId);
    if (!cinema) {
      throw new Error(`Cinema with ID ${input.cinemaId} not found`);
    }

    // Create room
    const room = new Room(
      undefined, // id will be generated by repository/db
      input.cinemaId,
      input.roomName,
      input.capacitySeat
    );

    await this.roomRepository.create(room);

    return {
      roomId: room.id as string,
    };
  }
}
